#ifndef __CONSTANTS_H__

#define GAPI_URL "/macros/s/AKfycbwT7m_cp2keFPEMwNM5MMR_a48S5N41LG9w1iQ-zFMABv0YHZ-5y_c5rTSoiM082CF8tw/exec"

#define DEFAULT_BRIGHTNESS 30
#define DEFAULT_PALETTE 2
#define DEFAULT_SPEED 10
#define DEFAULT_DYNAMIC 1
#define DEFAULT_LEFT 1

#endif